# Generated by Django 5.0.6 on 2024-07-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Vendedor', 'Vendedor'), ('Usuario', 'Cliente')], default='Usuario', max_length=10),
        ),
    ]
