# Generated by Django 5.0.6 on 2024-07-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.CharField(choices=[('5%', '5%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('25%', '25%')], max_length=10),
        ),
    ]
