# Generated by Django 5.0.6 on 2024-07-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_saleitem_discount_alter_saleitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Vendedor', 'Vendedor'), ('Cliente', 'Cliente')], default='Cliente', max_length=10),
        ),
    ]
