# Generated by Django 5.0.6 on 2024-07-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='discount',
            field=models.CharField(blank=True, choices=[('5%', '5%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('25%', '25%')], max_length=10, null=True),
        ),
    ]
